some cleaning
ISeal-plugin-developement/PowerGems pull request #1
Opened 2024-05-15 20:08 UTC by LunarcatOwO

Did some formating,
Also removed 2 imports from one file as they were not being used!

**NOT SURE IF IT WORKS, PLEASE TEST BEFORE MERGING**

2024-05-16 08:19 UTC, iseal56 requested changes
Generally good, needs some minor changes for clarity and some testing

2024-05-16 08:19 UTC, iseal56 commented on src/main/java/me/iseal/powergems/gems/IronGem.java
> +                ;
Why is this here?

2024-05-16 08:19 UTC, iseal56 commented on src/main/java/me/iseal/powergems/listeners/inventoryCloseListener.java
> +        // checkIfMultipleGems(plr);
Its a commented function call, don't add the space

2024-05-16 08:19 UTC, iseal56 commented on src/main/java/me/iseal/powergems/listeners/passivePowerListeners/damageListener.java
> +                    PersistentDataType.STRING))) {
Keep this as it was. It's the type of the object

2024-05-16 08:19 UTC, iseal56 commented on src/main/java/me/iseal/powergems/listeners/useEvent.java
> +                    player.sendMessage(ChatColor.DARK_RED + "You can't use gems for another "
Keep this as it was, it's clearer as the message is only 1 line in game

2024-05-16 08:19 UTC, iseal56 commented on src/main/java/me/iseal/powergems/managers/CooldownManager.java
> +                        .add(new CooldownObject(player, fromClass, (time * 500) + System.currentTimeMillis()));
Keep this as it was, dont separate the object from the function call

2024-05-16 08:19 UTC, iseal56 commented on src/main/java/me/iseal/powergems/managers/CooldownManager.java
> +                        .add(new CooldownObject(player, fromClass, (time * 500) + System.currentTimeMillis()));
Same as before

2024-05-16 08:19 UTC, iseal56 commented on src/main/java/me/iseal/powergems/managers/GemManager.java
> +                    + "Gem");
Move this up a line, keep the other newline

2024-05-16 08:19 UTC, iseal56 commented on src/main/java/me/iseal/powergems/managers/RecipeManager.java
> +                    /*
Can remove this part safely

2024-05-16 08:19 UTC, iseal56 commented on src/main/resources/plugin.yml
> +version: "${project.version}"
Keep as before

2024-05-16 08:19 UTC, iseal56 commented on src/main/resources/plugin.yml
> +api-version: "1.19"
Keep as before

2024-05-16 08:19 UTC, iseal56 commented on src/main/resources/plugin.yml
> +    children:
Needs testing, might not work

2024-05-16 19:59 UTC, LunarcatOwO commented on src/main/resources/plugin.yml
> +    children:
Test it.

2024-05-17 06:18 UTC, iseal56 requested changes
Almost done, just need a couple of changes

2024-05-17 06:18 UTC, iseal56 commented on src/main/java/me/iseal/powergems/gems/IronGem.java
> +            if (op.isOnline()) {;
Remove the semicolon. its useless

2024-05-17 06:18 UTC, iseal56 commented on src/main/java/me/iseal/powergems/listeners/passivePowerListeners/damageListener.java
> +        if (!event.getCause().equals(EntityDamageEvent.DamageCause.FALL)) return;
This line can stay as before

2024-05-17 06:18 UTC, iseal56 commented on src/main/java/me/iseal/powergems/listeners/passivePowerListeners/damageListener.java
> +        if (!event.getCause().equals(EntityDamageEvent.DamageCause.FALL)) return;
So only the return statement

2024-05-17 12:38 UTC, iseal56 approved these changes
Every issue fixed

2024-05-17 12:38 UTC, merged