added some Added a lot of null safety checks and some other small imp…
ISeal-plugin-developement/PowerGems pull request #25
Opened 2024-12-17 15:37 UTC by leonard-new

Added a lot of null safety checks 

Also replaced valueOf with parseInt

2024-12-17 16:10 UTC, iseal56 requested changes
Generally good. Some requireNonNull are redundant and all requirenonnull should probably be remade with an internal func to make sure to use ExceptionHandler if the value is null.
For now using requireNonNull and parseInt is fine.
Thanks for making a PR btw!

2024-12-17 16:10 UTC, iseal56 commented on src/main/java/dev/iseal/powergems/commands/GiveGemCommand.java
> +        if (!plr.hasPermission(Objects.requireNonNull(command.getPermission()))) {
This type of requireNonNull is redundant. command#getPermission will always return a valid permission since its written in the plugin.yml

2024-12-17 16:10 UTC, iseal56 commented on src/main/java/dev/iseal/powergems/commands/GiveAllGemCommand.java
> +        if (!plr.hasPermission(Objects.requireNonNull(command.getPermission()))) {
Same as earlier. This type of requireNonNull is redundant. command#getPermission will always return a valid permission since its written in the plugin.yml

2024-12-17 16:10 UTC, iseal56 commented on src/main/java/dev/iseal/powergems/commands/DebugCommand.java
> +        if (!plr.hasPermission(Objects.requireNonNull(command.getPermission()))) {
Same as earlier. This type of requireNonNull is redundant. command#getPermission will always return a valid permission since its written in the plugin.yml

2024-12-17 16:10 UTC, iseal56 commented on src/main/java/dev/iseal/powergems/commands/CheckUpdateCommand.java
> +        if (sender.hasPermission(Objects.requireNonNull(command.getPermission()))) {
Same as earlier. This type of requireNonNull is redundant. command#getPermission will always return a valid permission since its written in the plugin.yml

2024-12-17 16:10 UTC, iseal56 commented on src/main/java/dev/iseal/powergems/PowerGems.java
> +        Objects.requireNonNull(Bukkit.getServer().getPluginCommand("givegem")).setExecutor(new GiveGemCommand());
This requireNonNull is redundant as the command is registered in the plugin.yml.

2024-12-17 18:18 UTC, leonard-new commented
i just wanna ask is there anything i can help with like, fix a bug or something beacuse i dont have any project of mines to work on right now and  i can help

2025-01-01 21:26 UTC, iseal56 commented
DM me on discord if you want me to tell you what to work on

2025-01-02 08:36 UTC, leonard-new commented
K

2025-01-04 12:17 UTC, closed without merging