added Powergems tag
ISeal-plugin-developement/PowerGems pull request #3
Opened 2024-06-26 19:12 UTC by LunarcatOwO

Added the powergems tag to everything I think that would be sent to console

2024-06-26 20:24 UTC, iseal56 requested changes
Generally good, try to instanciate gcm if not instanciated already though.

2024-06-26 20:24 UTC, iseal56 commented on src/main/java/me/iseal/powergems/commands/debugCommand.java
> -            plr.sendMessage(ChatColor.DARK_RED + "You do not have permission to execute this command.");
Why was the ChatColor removed here?

2024-06-26 20:24 UTC, iseal56 commented on src/main/java/me/iseal/powergems/commands/giveAllGemCommand.java
> -            plr.sendMessage(ChatColor.DARK_RED + "You do not have permission to execute this command.");
Same as before, why was the chatcolor removed?

2024-07-03 06:30 UTC, iseal56 reviewed
Could be pushed, but you really should instantiate GeneralConfigManager every time it is used more than once in a class.

2024-07-03 11:04 UTC, LunarcatOwO commented
Alr :/

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: ISeal56 ***@***.***>
Sent: Wednesday, July 3, 2024 3:31:08 AM
To: ISeal-plugin-developement/PowerGems ***@***.***>
Cc: LunarcatOwO ***@***.***>; Author ***@***.***>
Subject: Re: [ISeal-plugin-developement/PowerGems] added Powergems tag (PR #3)


@iseal56 commented on this pull request.

Could be pushed, but you really should instantiate GeneralConfigManager every time it is used more than once in a class.

—
Reply to this email directly, view it on GitHub<https://github.com/ISeal-plugin-developement/PowerGems/pull/3#pullrequestreview-2155565653>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/ANBSD6IT5INAG3D7W34B45LZKOLCZAVCNFSM6AAAAABJ6PXZMKVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDCNJVGU3DKNRVGM>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2024-09-26 23:51 UTC, closed without merging